# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.chat_completion_response import ChatCompletionResponse

class TestChatCompletionResponse(unittest.TestCase):
    """ChatCompletionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionResponse:
        """Test ChatCompletionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionResponse`
        """
        model = ChatCompletionResponse()
        if include_optional:
            return ChatCompletionResponse(
                id = '',
                object = 'chat.completion',
                created = 56,
                model = '',
                choices = [
                    deeprelay_sdk.models.chat_choice.ChatChoice(
                        index = 56, 
                        message = deeprelay_sdk.models.chat_message.ChatMessage(
                            role = 'system', 
                            content = '', ), 
                        finish_reason = 'stop', )
                    ],
                usage = deeprelay_sdk.models.usage.Usage(
                    prompt_tokens = 56, 
                    completion_tokens = 56, 
                    total_tokens = 56, )
            )
        else:
            return ChatCompletionResponse(
                id = '',
                object = 'chat.completion',
                created = 56,
                model = '',
                choices = [
                    deeprelay_sdk.models.chat_choice.ChatChoice(
                        index = 56, 
                        message = deeprelay_sdk.models.chat_message.ChatMessage(
                            role = 'system', 
                            content = '', ), 
                        finish_reason = 'stop', )
                    ],
                usage = deeprelay_sdk.models.usage.Usage(
                    prompt_tokens = 56, 
                    completion_tokens = 56, 
                    total_tokens = 56, ),
        )
        """

    def testChatCompletionResponse(self):
        """Test ChatCompletionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
