# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.embedding import Embedding

class TestEmbedding(unittest.TestCase):
    """Embedding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embedding:
        """Test Embedding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embedding`
        """
        model = Embedding()
        if include_optional:
            return Embedding(
                object = 'embedding',
                embedding = [
                    1.337
                    ],
                index = 56
            )
        else:
            return Embedding(
                object = 'embedding',
                embedding = [
                    1.337
                    ],
                index = 56,
        )
        """

    def testEmbedding(self):
        """Test Embedding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
