# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.subscription_usage import SubscriptionUsage

class TestSubscriptionUsage(unittest.TestCase):
    """SubscriptionUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionUsage:
        """Test SubscriptionUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionUsage`
        """
        model = SubscriptionUsage()
        if include_optional:
            return SubscriptionUsage(
                period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                weighted_input_tokens = 56,
                weighted_output_tokens = 56,
                weekly_weighted_tokens = 56,
                cost_micro_cents = 56
            )
        else:
            return SubscriptionUsage(
                period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                weighted_input_tokens = 56,
                weighted_output_tokens = 56,
                weekly_weighted_tokens = 56,
                cost_micro_cents = 56,
        )
        """

    def testSubscriptionUsage(self):
        """Test SubscriptionUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
