# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.model_rate import ModelRate

class TestModelRate(unittest.TestCase):
    """ModelRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelRate:
        """Test ModelRate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelRate`
        """
        model = ModelRate()
        if include_optional:
            return ModelRate(
                input_per_1m_tokens_cents = 56,
                input_per_1m_tokens_microcents = 56,
                cached_input_per_1m_tokens_cents = 56,
                cached_input_per_1m_tokens_microcents = 56,
                output_per_1m_tokens_cents = 56,
                output_per_1m_tokens_microcents = 56
            )
        else:
            return ModelRate(
        )
        """

    def testModelRate(self):
        """Test ModelRate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
