# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.subscription_quota import SubscriptionQuota

class TestSubscriptionQuota(unittest.TestCase):
    """SubscriptionQuota unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionQuota:
        """Test SubscriptionQuota
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionQuota`
        """
        model = SubscriptionQuota()
        if include_optional:
            return SubscriptionQuota(
                input_tokens_monthly = 56,
                output_tokens_monthly = 56,
                weekly_tokens = 56,
                max_usage_micro_cents = 56,
                payg_discount_bp = 56
            )
        else:
            return SubscriptionQuota(
                input_tokens_monthly = 56,
                output_tokens_monthly = 56,
                weekly_tokens = 56,
                max_usage_micro_cents = 56,
                payg_discount_bp = 56,
        )
        """

    def testSubscriptionQuota(self):
        """Test SubscriptionQuota"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
