# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.referral import Referral

class TestReferral(unittest.TestCase):
    """Referral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Referral:
        """Test Referral
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Referral`
        """
        model = Referral()
        if include_optional:
            return Referral(
                code = 'GPU-7KQ2-M4XP',
                invite_url = 'https://deeprelay.ai/r/GPU-7KQ2-M4XP',
                pending = 56,
                qualified = 56,
                settled = 56,
                earned_cents = 56,
                reward_cents = 56,
                referee_reward_cents = 56,
                qualify_spend_cents = 56,
                hold_days = 56,
                referred = deeprelay_sdk.models.referee_status.RefereeStatus(
                    status = 'pending', 
                    spent_cents = 56, 
                    qualify_spend_cents = 56, 
                    reward_cents = 56, 
                    qualified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    hold_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return Referral(
                code = 'GPU-7KQ2-M4XP',
                invite_url = 'https://deeprelay.ai/r/GPU-7KQ2-M4XP',
                pending = 56,
                qualified = 56,
                settled = 56,
                earned_cents = 56,
                reward_cents = 56,
                referee_reward_cents = 56,
                qualify_spend_cents = 56,
                hold_days = 56,
        )
        """

    def testReferral(self):
        """Test Referral"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
