# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.api.operations_api import OperationsApi


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OperationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_operation(self) -> None:
        """Test case for get_operation

        Get an async operation status
        """
        pass


if __name__ == '__main__':
    unittest.main()
