# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.subscription_portal_session import SubscriptionPortalSession

class TestSubscriptionPortalSession(unittest.TestCase):
    """SubscriptionPortalSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionPortalSession:
        """Test SubscriptionPortalSession
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionPortalSession`
        """
        model = SubscriptionPortalSession()
        if include_optional:
            return SubscriptionPortalSession(
                portal_url = ''
            )
        else:
            return SubscriptionPortalSession(
                portal_url = '',
        )
        """

    def testSubscriptionPortalSession(self):
        """Test SubscriptionPortalSession"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
