# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.api.billing_api import BillingApi


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingApi()

    def tearDown(self) -> None:
        pass

    def test_create_crypto_deposit(self) -> None:
        """Test case for create_crypto_deposit

        Create a stablecoin deposit
        """
        pass

    def test_get_balance(self) -> None:
        """Test case for get_balance

        Get the org credit balance
        """
        pass

    def test_get_deposit(self) -> None:
        """Test case for get_deposit

        Get one stablecoin deposit
        """
        pass

    def test_get_spending_limit(self) -> None:
        """Test case for get_spending_limit

        Get the org spending limit
        """
        pass

    def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Get the org subscription status and quota usage
        """
        pass

    def test_list_deposits(self) -> None:
        """Test case for list_deposits

        List stablecoin deposits
        """
        pass

    def test_update_spending_limit(self) -> None:
        """Test case for update_spending_limit

        Set the org spending limit
        """
        pass


if __name__ == '__main__':
    unittest.main()
