# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.api.usage_api import UsageApi


class TestUsageApi(unittest.TestCase):
    """UsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsageApi()

    def tearDown(self) -> None:
        pass

    def test_list_usage(self) -> None:
        """Test case for list_usage

        Time-bucketed usage
        """
        pass


if __name__ == '__main__':
    unittest.main()
