# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deeprelay_sdk.models.subscription import Subscription

class TestSubscription(unittest.TestCase):
    """Subscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subscription:
        """Test Subscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscription`
        """
        model = Subscription()
        if include_optional:
            return Subscription(
                subscribed = True,
                status = '',
                cancel_at_period_end = True,
                current_period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                quota = deeprelay_sdk.models.subscription_quota.SubscriptionQuota(
                    input_tokens_monthly = 56, 
                    output_tokens_monthly = 56, 
                    weekly_tokens = 56, 
                    max_usage_micro_cents = 56, 
                    payg_discount_bp = 56, ),
                usage = deeprelay_sdk.models.subscription_usage.SubscriptionUsage(
                    period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    weighted_input_tokens = 56, 
                    weighted_output_tokens = 56, 
                    weekly_weighted_tokens = 56, 
                    cost_micro_cents = 56, )
            )
        else:
            return Subscription(
                subscribed = True,
                status = '',
                cancel_at_period_end = True,
                quota = deeprelay_sdk.models.subscription_quota.SubscriptionQuota(
                    input_tokens_monthly = 56, 
                    output_tokens_monthly = 56, 
                    weekly_tokens = 56, 
                    max_usage_micro_cents = 56, 
                    payg_discount_bp = 56, ),
        )
        """

    def testSubscription(self):
        """Test Subscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
