# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Balance(BaseModel):
    """
    The organization's credit balance with its auto-pay configuration and live burn rate. Mirrors the dashboard's balance contract field for field. No payment-instrument detail appears here — saved cards live behind separate admin-only routes. 
    """ # noqa: E501
    balance_cents: StrictInt = Field(description="Remaining credit in USD cents. May be negative when usage has outrun the balance.")
    balance_dollars: Union[StrictFloat, StrictInt] = Field(description="The same figure in dollars, for display.")
    auto_pay_enabled: StrictBool
    auto_pay_threshold_cents: StrictInt = Field(description="Auto-pay triggers when the balance falls below this. Meaningful only when auto_pay_enabled.")
    auto_pay_amount_cents: StrictInt = Field(description="Amount auto-pay charges when it triggers. Meaningful only when auto_pay_enabled.")
    burn_cents_per_hour: Optional[StrictInt] = Field(description="Live burn rate in USD cents per hour: the committed hourly price of every instance that is live, counted from launch — so instances still creating, provisioning or booting are included, not only those that have reached running. 0 when nothing is live.  `null` means the burn rate could not be determined. Treat that as unknown, never as 0: reading an unavailable burn rate as \"nothing running\" reports unbounded runway to an organization that may be minutes from empty.")
    __properties: ClassVar[List[str]] = ["balance_cents", "balance_dollars", "auto_pay_enabled", "auto_pay_threshold_cents", "auto_pay_amount_cents", "burn_cents_per_hour"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Balance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if burn_cents_per_hour (nullable) is None
        # and model_fields_set contains the field
        if self.burn_cents_per_hour is None and "burn_cents_per_hour" in self.model_fields_set:
            _dict['burn_cents_per_hour'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Balance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "balance_cents": obj.get("balance_cents"),
            "balance_dollars": obj.get("balance_dollars"),
            "auto_pay_enabled": obj.get("auto_pay_enabled"),
            "auto_pay_threshold_cents": obj.get("auto_pay_threshold_cents"),
            "auto_pay_amount_cents": obj.get("auto_pay_amount_cents"),
            "burn_cents_per_hour": obj.get("burn_cents_per_hour")
        })
        return _obj


