# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from deeprelay_sdk.models.embeddings_request_input import EmbeddingsRequestInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EmbeddingsRequest(BaseModel):
    """
    EmbeddingsRequest
    """ # noqa: E501
    model: StrictStr = Field(description="Canonical embedding model id, e.g. \"deeprelay/qwen3-embedding-8b\".")
    input: EmbeddingsRequestInput
    encoding_format: Optional[StrictStr] = Field(default='float', description="Only \"float\" is supported. A value of \"base64\" is rejected with invalid_request_error / unsupported_parameter.")
    dimensions: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Requested output dimensionality, for models that support truncated (Matryoshka) embeddings. Passed through to the model when set.")
    user: Optional[StrictStr] = Field(default=None, description="Opaque end-user identifier for abuse tracing. Optional.")
    __properties: ClassVar[List[str]] = ["model", "input", "encoding_format", "dimensions", "user"]

    @field_validator('encoding_format')
    def encoding_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['float']):
            raise ValueError("must be one of enum values ('float')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmbeddingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmbeddingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "input": EmbeddingsRequestInput.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "encoding_format": obj.get("encoding_format") if obj.get("encoding_format") is not None else 'float',
            "dimensions": obj.get("dimensions"),
            "user": obj.get("user")
        })
        return _obj


