# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InferencePreflight(BaseModel):
    """
    The verdict for one (organization, model) pair: what would happen if the model were invoked right now. 
    """ # noqa: E501
    model: StrictStr = Field(description="The canonical catalog id the request resolved to.")
    verdict: StrictStr = Field(description="`ok` — the request will be served (covered by the plan, or payable). `warn` — it will be served AND charged in a way the caller may not expect. `block` — it will be refused (402 or 429).")
    reason: Optional[StrictStr] = Field(default=None, description="Stable code explaining the verdict, for clients that need their own wording. Absent on a plain `ok` that needs no explanation.")
    message: StrictStr = Field(description="A ready-to-print sentence, phrased for this exact plan/credit combination. Prefer it over composing one from verdict and reason: it improves without a client release.")
    plan_covered: StrictBool = Field(description="Whether the subscription tier covers this model. A property of the PLATFORM, not of the caller — it stays true for an organization that has no subscription, which is what makes the \"this is included in the plan\" upsell honest.")
    subscribed: StrictBool = Field(description="Whether the organization is entitled to the plan right now.")
    funded: StrictBool = Field(description="Whether a pay-as-you-go request could be paid for right now: a positive credit balance AND no self-set spending cap already at its limit. A boolean and never a figure — this route is on the inference read scope and must not disclose the balance.")
    __properties: ClassVar[List[str]] = ["model", "verdict", "reason", "message", "plan_covered", "subscribed", "funded"]

    @field_validator('verdict')
    def verdict_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ok', 'warn', 'block']):
            raise ValueError("must be one of enum values ('ok', 'warn', 'block')")
        return value

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['plan_covered', 'payg', 'not_plan_covered', 'subscription_quota_exhausted', 'insufficient_balance', 'daily_limit_reached', 'monthly_limit_reached', 'preflight_unavailable']):
            raise ValueError("must be one of enum values ('plan_covered', 'payg', 'not_plan_covered', 'subscription_quota_exhausted', 'insufficient_balance', 'daily_limit_reached', 'monthly_limit_reached', 'preflight_unavailable')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InferencePreflight from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InferencePreflight from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "verdict": obj.get("verdict"),
            "reason": obj.get("reason"),
            "message": obj.get("message"),
            "plan_covered": obj.get("plan_covered"),
            "subscribed": obj.get("subscribed"),
            "funded": obj.get("funded")
        })
        return _obj


