# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelRate(BaseModel):
    """
    One per-1M-token rate triple, in rounded cents and exact micro-cents (1e-6 cent). Prefer the micro-cent fields for arithmetic; cached rates are routinely sub-cent and their cents field is then omitted.
    """ # noqa: E501
    input_per_1m_tokens_cents: Optional[StrictInt] = None
    input_per_1m_tokens_microcents: Optional[StrictInt] = None
    cached_input_per_1m_tokens_cents: Optional[StrictInt] = None
    cached_input_per_1m_tokens_microcents: Optional[StrictInt] = None
    output_per_1m_tokens_cents: Optional[StrictInt] = None
    output_per_1m_tokens_microcents: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["input_per_1m_tokens_cents", "input_per_1m_tokens_microcents", "cached_input_per_1m_tokens_cents", "cached_input_per_1m_tokens_microcents", "output_per_1m_tokens_cents", "output_per_1m_tokens_microcents"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelRate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelRate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input_per_1m_tokens_cents": obj.get("input_per_1m_tokens_cents"),
            "input_per_1m_tokens_microcents": obj.get("input_per_1m_tokens_microcents"),
            "cached_input_per_1m_tokens_cents": obj.get("cached_input_per_1m_tokens_cents"),
            "cached_input_per_1m_tokens_microcents": obj.get("cached_input_per_1m_tokens_microcents"),
            "output_per_1m_tokens_cents": obj.get("output_per_1m_tokens_cents"),
            "output_per_1m_tokens_microcents": obj.get("output_per_1m_tokens_microcents")
        })
        return _obj


