# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from deeprelay_sdk.models.model_rate import ModelRate
from deeprelay_sdk.models.peak_window import PeakWindow
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ModelPricing(BaseModel):
    """
    ModelPricing
    """ # noqa: E501
    currency: Optional[StrictStr] = None
    input_per_1m_tokens_cents: Optional[StrictInt] = None
    output_per_1m_tokens_cents: Optional[StrictInt] = None
    cached_input_per_1m_tokens_microcents: Optional[StrictInt] = Field(default=None, description="Exact per-1M-token rate in micro-cents (1e-6 cent) for the cache-HIT part of a chat prompt (usage.prompt_tokens_details.cached_tokens). Present only on models with a published cached-input rate; absent means no discount — every prompt token bills at input_per_1m_tokens_cents. Treat this field as the presence signal: cached rates are routinely sub-cent, so the rounded cents field below is often omitted.")
    cached_input_per_1m_tokens_cents: Optional[StrictInt] = Field(default=None, description="cached_input_per_1m_tokens_microcents rounded to whole cents; omitted when the exact rate rounds below half a cent.")
    per_image_cents: Optional[StrictInt] = None
    per_image_microcents: Optional[StrictInt] = Field(default=None, description="Exact per-image rate in micro-cents (1e-6 cent). Prefer this for image models — per_image_cents rounds sub-cent prices to 0.")
    per_mpxl_microcents: Optional[StrictInt] = Field(default=None, description="Price per output megapixel in micro-cents (1e-6 cent) for image models metered per megapixel. Mutually exclusive with the per-image fields.")
    per_video_microcents: Optional[StrictInt] = Field(default=None, description="Representative per-clip price in micro-cents (1e-6 cent) for video models — a \"from\" price taken from the provider's published example rate.")
    per_video_second_cents: Optional[StrictInt] = None
    per_video_second_microcents: Optional[StrictInt] = Field(default=None, description="Exact per-second-of-output-video rate in micro-cents (1e-6 cent). Prefer this for video models.")
    period: Optional[StrictStr] = Field(default=None, description="Present only on a model priced by time of day. Which side of the peak schedule the instant this response was rendered falls on; the flat rate fields above are the rates in effect at that instant. A request is billed at the rate in effect when it ARRIVES (UTC), so a caller planning a call for later should price it from `peak` / `off_peak` and `peak_windows_utc`.")
    peak_windows_utc: Optional[List[PeakWindow]] = Field(default=None, description="The daily UTC ranges during which the `peak` rates apply, start inclusive and end exclusive (\"24:00\" is a valid end; a range whose end sorts before its start wraps midnight). Present only on a model priced by time of day.")
    peak: Optional[ModelRate] = None
    off_peak: Optional[ModelRate] = None
    __properties: ClassVar[List[str]] = ["currency", "input_per_1m_tokens_cents", "output_per_1m_tokens_cents", "cached_input_per_1m_tokens_microcents", "cached_input_per_1m_tokens_cents", "per_image_cents", "per_image_microcents", "per_mpxl_microcents", "per_video_microcents", "per_video_second_cents", "per_video_second_microcents", "period", "peak_windows_utc", "peak", "off_peak"]

    @field_validator('period')
    def period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['peak', 'off_peak']):
            raise ValueError("must be one of enum values ('peak', 'off_peak')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelPricing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in peak_windows_utc (list)
        _items = []
        if self.peak_windows_utc:
            for _item_peak_windows_utc in self.peak_windows_utc:
                if _item_peak_windows_utc:
                    _items.append(_item_peak_windows_utc.to_dict())
            _dict['peak_windows_utc'] = _items
        # override the default output from pydantic by calling `to_dict()` of peak
        if self.peak:
            _dict['peak'] = self.peak.to_dict()
        # override the default output from pydantic by calling `to_dict()` of off_peak
        if self.off_peak:
            _dict['off_peak'] = self.off_peak.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelPricing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "input_per_1m_tokens_cents": obj.get("input_per_1m_tokens_cents"),
            "output_per_1m_tokens_cents": obj.get("output_per_1m_tokens_cents"),
            "cached_input_per_1m_tokens_microcents": obj.get("cached_input_per_1m_tokens_microcents"),
            "cached_input_per_1m_tokens_cents": obj.get("cached_input_per_1m_tokens_cents"),
            "per_image_cents": obj.get("per_image_cents"),
            "per_image_microcents": obj.get("per_image_microcents"),
            "per_mpxl_microcents": obj.get("per_mpxl_microcents"),
            "per_video_microcents": obj.get("per_video_microcents"),
            "per_video_second_cents": obj.get("per_video_second_cents"),
            "per_video_second_microcents": obj.get("per_video_second_microcents"),
            "period": obj.get("period"),
            "peak_windows_utc": [PeakWindow.from_dict(_item) for _item in obj["peak_windows_utc"]] if obj.get("peak_windows_utc") is not None else None,
            "peak": ModelRate.from_dict(obj["peak"]) if obj.get("peak") is not None else None,
            "off_peak": ModelRate.from_dict(obj["off_peak"]) if obj.get("off_peak") is not None else None
        })
        return _obj


