# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from deeprelay_sdk.models.referee_status import RefereeStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Referral(BaseModel):
    """
    The organization's referral-program view: its invite link, the program terms, its referrer stats, and (only when it was itself referred) its referee progress. Amounts are USD cents. 
    """ # noqa: E501
    code: StrictStr = Field(description="The organization's shareable referral code, e.g. `GPU-7KQ2-M4XP`.", json_schema_extra={"examples": ["GPU-7KQ2-M4XP"]})
    invite_url: StrictStr = Field(description="The ready-to-share invite link, `{site}/r/{code}`.", json_schema_extra={"examples": ["https://deeprelay.ai/r/GPU-7KQ2-M4XP"]})
    pending: StrictInt = Field(description="Friends who signed up through the link but have not yet reached the spend gate.")
    qualified: StrictInt = Field(description="Friends past the spend gate whose reward is inside the chargeback hold.")
    settled: StrictInt = Field(description="Referrals that have paid out.")
    earned_cents: StrictInt = Field(description="Total credit paid to this organization as a referrer.")
    reward_cents: StrictInt = Field(description="Credit paid to the referrer per settled referral.")
    referee_reward_cents: StrictInt = Field(description="Credit paid to the referred friend per settled referral.")
    qualify_spend_cents: StrictInt = Field(description="The friend's cumulative inference spend that qualifies a referral.")
    hold_days: StrictInt = Field(description="Days between qualification and payout (chargeback hold).")
    referred: Optional[RefereeStatus] = None
    __properties: ClassVar[List[str]] = ["code", "invite_url", "pending", "qualified", "settled", "earned_cents", "reward_cents", "referee_reward_cents", "qualify_spend_cents", "hold_days", "referred"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Referral from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of referred
        if self.referred:
            _dict['referred'] = self.referred.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Referral from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "invite_url": obj.get("invite_url"),
            "pending": obj.get("pending"),
            "qualified": obj.get("qualified"),
            "settled": obj.get("settled"),
            "earned_cents": obj.get("earned_cents"),
            "reward_cents": obj.get("reward_cents"),
            "referee_reward_cents": obj.get("referee_reward_cents"),
            "qualify_spend_cents": obj.get("qualify_spend_cents"),
            "hold_days": obj.get("hold_days"),
            "referred": RefereeStatus.from_dict(obj["referred"]) if obj.get("referred") is not None else None
        })
        return _obj


