# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RefereeStatus(BaseModel):
    """
    Present only when the organization signed up through someone else's invite link: where that referral sits and how far the organization is from unlocking its own reward. 
    """ # noqa: E501
    status: StrictStr = Field(description="Lifecycle state. `pending` until the spend gate is met; `qualified` inside the hold; `settled` once paid.")
    spent_cents: StrictInt = Field(description="Cumulative inference spend so far.")
    qualify_spend_cents: StrictInt = Field(description="The spend that qualifies the referral.")
    reward_cents: StrictInt = Field(description="What this organization receives on settlement.")
    qualified_at: Optional[datetime] = Field(default=None, description="When the spend gate was met. Absent while pending.")
    hold_until: Optional[datetime] = Field(default=None, description="When the hold ends and both halves pay out. Absent while pending.")
    settled_at: Optional[datetime] = Field(default=None, description="When the reward was paid. Absent until settled.")
    __properties: ClassVar[List[str]] = ["status", "spent_cents", "qualify_spend_cents", "reward_cents", "qualified_at", "hold_until", "settled_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'qualified', 'settled', 'rejected']):
            raise ValueError("must be one of enum values ('pending', 'qualified', 'settled', 'rejected')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RefereeStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RefereeStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "spent_cents": obj.get("spent_cents"),
            "qualify_spend_cents": obj.get("qualify_spend_cents"),
            "reward_cents": obj.get("reward_cents"),
            "qualified_at": obj.get("qualified_at"),
            "hold_until": obj.get("hold_until"),
            "settled_at": obj.get("settled_at")
        })
        return _obj


