# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SubscriptionUsage(BaseModel):
    """
    Consumption against the quota, from the same factor-weighted read the request-time gate evaluates — so this meter and enforcement cannot disagree.  Present only for an entitled subscription whose meter could be read. Its absence is never a statement that nothing was used. 
    """ # noqa: E501
    period_start: datetime = Field(description="Start of the window the period figures were summed over: the subscription's current period, or the UTC calendar month when the billing provider has not reported one yet.")
    period_end: datetime = Field(description="End of that window.")
    weighted_input_tokens: StrictInt = Field(description="Weighted input tokens spent this period, against `quota.input_tokens_monthly`.")
    weighted_output_tokens: StrictInt = Field(description="Weighted output tokens spent this period, against `quota.output_tokens_monthly`.")
    weekly_weighted_tokens: StrictInt = Field(description="Weighted input+output tokens over the trailing 7 days, against `quota.weekly_tokens`. A rolling figure, not a period one — it can be non-zero moments after a period rolls over.")
    cost_micro_cents: StrictInt = Field(description="List-price metered cost of this period's plan traffic in micro-cents (1e-6 cent), against `quota.max_usage_micro_cents`.")
    __properties: ClassVar[List[str]] = ["period_start", "period_end", "weighted_input_tokens", "weighted_output_tokens", "weekly_weighted_tokens", "cost_micro_cents"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubscriptionUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubscriptionUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "period_start": obj.get("period_start"),
            "period_end": obj.get("period_end"),
            "weighted_input_tokens": obj.get("weighted_input_tokens"),
            "weighted_output_tokens": obj.get("weighted_output_tokens"),
            "weekly_weighted_tokens": obj.get("weekly_weighted_tokens"),
            "cost_micro_cents": obj.get("cost_micro_cents")
        })
        return _obj


