# coding: utf-8

"""
    deeprelay Public Developer API

    Programmatic API for deeprelay. Authenticate with API keys minted from the dashboard. See https://deeprelay.ai/docs for details. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@deeprelay.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from deeprelay_sdk.models.subscription_plan import SubscriptionPlan
from deeprelay_sdk.models.subscription_quota import SubscriptionQuota
from deeprelay_sdk.models.subscription_usage import SubscriptionUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Subscription(BaseModel):
    """
    The organization's flat subscription tier: entitlement, billing period, the configured quota, and consumption against it. The console and this endpoint assemble it from the same source, so the two surfaces cannot report different numbers. 
    """ # noqa: E501
    subscribed: StrictBool = Field(description="Whether the organization is entitled to the plan right now. Only an `active` or `trialing` subscription entitles, including a short grace window past the period end that absorbs renewal webhook lag; a failed payment (`past_due`) cuts access immediately. Render from this; do not re-derive entitlement from `status` and the period bounds.")
    status: StrictStr = Field(description="Raw subscription status — \"active\", \"trialing\", \"past_due\", \"canceled\" and so on — or \"none\" when the organization never subscribed.")
    cancel_at_period_end: StrictBool = Field(description="Whether the subscription stops at the end of the current period instead of renewing.")
    current_period_start: Optional[datetime] = Field(default=None, description="Start of the current billing period. Absent until the billing provider has reported a period for this subscription.")
    current_period_end: Optional[datetime] = Field(default=None, description="End of the current billing period. Absent under the same condition as current_period_start.")
    plan: SubscriptionPlan
    quota: SubscriptionQuota
    usage: Optional[SubscriptionUsage] = None
    __properties: ClassVar[List[str]] = ["subscribed", "status", "cancel_at_period_end", "current_period_start", "current_period_end", "plan", "quota", "usage"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quota
        if self.quota:
            _dict['quota'] = self.quota.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subscribed": obj.get("subscribed"),
            "status": obj.get("status"),
            "cancel_at_period_end": obj.get("cancel_at_period_end"),
            "current_period_start": obj.get("current_period_start"),
            "current_period_end": obj.get("current_period_end"),
            "plan": SubscriptionPlan.from_dict(obj["plan"]) if obj.get("plan") is not None else None,
            "quota": SubscriptionQuota.from_dict(obj["quota"]) if obj.get("quota") is not None else None,
            "usage": SubscriptionUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


